INSERT INTO meals (name, category, region, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, serving_unit, typical_serving)
SELECT * FROM (VALUES
('Masoor Dal',     'dal',   'general',     116, 9.0,  20.1,  0.4, 3.2, 'katori',      150),
('Toor Dal',       'dal',   'general',     118, 8.4,  21.0,  0.5, 3.0, 'katori',      150),
('Moong Dal',      'dal',   'general',     105, 7.6,  18.0,  0.4, 4.1, 'katori',      150),
('Chana Dal',      'dal',   'general',     164, 8.7,  27.0,  2.7, 7.6, 'katori',      150),
('Urad Dal',       'dal',   'general',     341, 25.0, 58.0,  1.6, 1.8, 'katori',      150),
('Rajma',          'dal',   'punjabi',     127, 8.7,  22.0,  0.5, 8.4, 'katori',      150),
('Chole',          'dal',   'punjabi',     164, 8.9,  27.0,  2.6, 6.2, 'katori',      150),
('Dal Makhani',    'dal',   'punjabi',     174, 9.0,  20.0,  6.5, 5.0, 'katori',      150),
('Steamed Rice',   'rice',  'general',      86, 1.8,  19.0,  0.1, 0.3, 'katori',      150),
('Brown Rice',     'rice',  'general',     111, 2.6,  23.0,  0.9, 1.8, 'katori',      150),
('Khichdi',        'rice',  'general',      92, 3.4,  17.0,  0.8, 1.2, 'katori',      200),
('Pulao',          'rice',  'general',     142, 3.2,  26.0,  2.8, 1.0, 'katori',      150),
('Biryani',        'rice',  'general',     187, 8.0,  28.0,  5.6, 1.1, 'katori',      200),
('Chapati',        'roti',  'general',      71, 2.7,  15.0,  0.4, 1.9, 'piece',        40),
('Jowar Bhakri',   'roti',  'konkan',       85, 2.7,  17.1,  0.8, 1.2, 'piece',        60),
('Bajra Roti',     'roti',  'general',      97, 3.6,  18.0,  1.4, 2.3, 'piece',        50),
('Paratha',        'roti',  'punjabi',     127, 3.2,  19.0,  4.0, 1.8, 'piece',        60),
('Naan',           'roti',  'punjabi',     262, 8.7,  46.0,  4.5, 1.9, 'piece',        80),
('Puri',           'roti',  'general',     175, 3.8,  24.0,  7.4, 1.2, 'piece',        35),
('Aloo Sabzi',     'sabzi', 'general',      98, 1.8,  20.0,  1.5, 2.0, 'katori',      150),
('Palak Paneer',   'sabzi', 'punjabi',     132, 7.0,   8.0,  8.0, 2.4, 'katori',      150),
('Bhindi Masala',  'sabzi', 'general',      64, 2.0,   7.0,  3.0, 3.2, 'katori',      150),
('Baingan Bharta', 'sabzi', 'punjabi',      78, 2.4,   8.0,  4.0, 3.4, 'katori',      150),
('Matar Paneer',   'sabzi', 'punjabi',     145, 8.0,  10.0,  9.0, 2.8, 'katori',      150),
('Gobi Sabzi',     'sabzi', 'general',      58, 2.5,   6.0,  2.5, 2.0, 'katori',      150),
('Mixed Veg',      'sabzi', 'general',      85, 3.0,  10.0,  3.5, 2.6, 'katori',      150),
('Butter Chicken', 'sabzi', 'punjabi',     180, 18.0,  5.0,  9.0, 0.5, 'katori',      150),
('Egg Curry',      'sabzi', 'general',     152, 11.0,  4.0,  9.5, 0.8, 'katori',      150),
('Fish Curry',     'sabzi', 'konkan',      142, 19.0,  4.0,  6.0, 0.4, 'katori',      150),
('Poha',           'snack', 'general',     130, 2.6,  24.0,  3.4, 0.9, 'katori',      150),
('Upma',           'snack', 'south_indian',145, 3.5,  25.0,  4.0, 1.4, 'katori',      150),
('Idli',           'snack', 'south_indian', 58, 2.7,  12.0,  0.1, 0.5, 'piece',        50),
('Dosa',           'snack', 'south_indian',168, 3.8,  28.0,  4.4, 0.6, 'piece',       100),
('Vada',           'snack', 'south_indian', 97, 2.5,  11.0,  4.9, 1.2, 'piece',        40),
('Dhokla',         'snack', 'general',     150, 6.0,  25.0,  2.5, 1.0, 'piece',        50),
('Samosa',         'snack', 'general',     262, 5.7,  31.0, 12.5, 2.3, 'piece',        70),
('Poori Sabzi',    'snack', 'general',     223, 4.8,  30.0,  9.4, 2.2, 'plate',       180),
('Paneer',         'dairy', 'general',     265, 18.3,  1.2, 20.8, 0.0, 'piece',       100),
('Curd',           'dairy', 'general',      61, 3.1,   4.7,  3.4, 0.0, 'katori',      150),
('Lassi',          'dairy', 'punjabi',      75, 3.5,   9.2,  2.5, 0.0, 'glass',       250),
('Chaas',          'dairy', 'general',      40, 3.3,   4.9,  0.9, 0.0, 'glass',       250),
('Milk',           'dairy', 'general',      61, 3.2,   4.7,  3.4, 0.0, 'glass',       250),
('Ghee',           'dairy', 'general',     900, 0.0,   0.0, 99.7, 0.0, 'tablespoon',   10),
('Banana',         'fruit', 'general',      89, 1.1,  23.0,  0.3, 2.6, 'piece',       120),
('Mango',          'fruit', 'general',      60, 0.8,  15.0,  0.4, 1.6, 'piece',       200),
('Papaya',         'fruit', 'general',      43, 0.5,  11.0,  0.3, 1.7, 'slice',       150),
('Guava',          'fruit', 'general',      68, 2.6,  14.0,  1.0, 5.4, 'piece',       100),
('Apple',          'fruit', 'general',      52, 0.3,  14.0,  0.2, 2.4, 'piece',       150),
('Solkadhi',       'konkan','konkan',        45, 1.5,   5.0,  2.0, 0.5, 'glass',       200),
('Amboli',         'konkan','konkan',       148, 5.2,  28.0,  1.4, 0.8, 'piece',        80),
('Modak',          'konkan','konkan',       180, 3.5,  35.0,  3.5, 1.2, 'piece',        60),
('Kombdi Vade',    'konkan','konkan',       265, 14.0, 28.0, 10.0, 1.5, 'plate',       250),
('Bombil Fry',     'konkan','konkan',        95, 18.0,  0.0,  2.5, 0.0, 'piece',        80)
) AS v(name, category, region, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, serving_unit, typical_serving)
WHERE NOT EXISTS (SELECT 1 FROM meals LIMIT 1);

INSERT INTO exercises (name, category, equipment, muscle_group, description, default_sets, default_reps)
SELECT * FROM (VALUES
-- Strength
('Push-ups',          'strength',    'none',           'chest',      'Classic bodyweight push-up', 3, 15),
('Diamond Push-ups',  'strength',    'none',           'chest',      'Hands close together, targets triceps', 3, 10),
('Pull-ups',          'strength',    'pullup_bar',      'back',       'Hang from bar, pull chest to bar', 3, 8),
('Chin-ups',          'strength',    'pullup_bar',      'back',       'Underhand grip pull-up', 3, 8),
('Squats',            'strength',    'none',           'legs',       'Bodyweight squat, knees track toes', 3, 20),
('Jump Squats',       'strength',    'none',           'legs',       'Explosive squat with jump', 3, 12),
('Lunges',            'strength',    'none',           'legs',       'Alternating forward lunges', 3, 12),
('Glute Bridge',      'strength',    'mat',            'legs',       'Lie on back, push hips up', 3, 15),
('Plank',             'strength',    'mat',            'core',       'Hold straight body position', 3, 30),
('Side Plank',        'strength',    'mat',            'core',       'Hold on one forearm', 3, 20),
('Crunches',          'strength',    'mat',            'core',       'Basic abdominal crunch', 3, 20),
('Leg Raises',        'strength',    'mat',            'core',       'Lie flat, raise legs to 90 degrees', 3, 15),
('Mountain Climbers', 'strength',    'none',           'core',       'Alternate driving knees to chest in plank', 3, 20),
('Dips',              'strength',    'none',           'arms',       'Use chair or parallel bars', 3, 12),
('Pike Push-ups',     'strength',    'none',           'shoulders',  'Inverted V position, lower head to floor', 3, 10),
('Superman',          'strength',    'mat',            'back',       'Lie face down, lift arms and legs', 3, 12),
-- Cardio
('Jumping Jacks',     'cardio',      'none',           'cardio',     'Arms and legs out simultaneously', 3, 30),
('Burpees',           'cardio',      'none',           'full_body',  'Squat, jump back to plank, push-up, jump up', 3, 10),
('High Knees',        'cardio',      'none',           'cardio',     'Run in place bringing knees to chest', 3, 30),
('Skipping',          'cardio',      'none',           'cardio',     'Jump rope or simulate the motion', 1, 100),
('Stair Climbing',    'cardio',      'none',           'legs',       'Walk or run up stairs', 3, 20),
('Box Steps',         'cardio',      'none',           'cardio',     'Step up and down on a stable surface', 3, 20),
-- Yoga
('Surya Namaskar',    'yoga',        'mat',            'full_body',  '12-pose sun salutation sequence', 1, 5),
('Warrior I',         'yoga',        'mat',            'legs',       'Lunge with arms raised overhead', 1, 5),
('Warrior II',        'yoga',        'mat',            'legs',       'Wide stance with arms parallel to floor', 1, 5),
('Downward Dog',      'yoga',        'mat',            'full_body',  'Inverted V stretch', 1, 5),
('Child''s Pose',     'yoga',        'mat',            'back',       'Kneel and stretch arms forward', 1, 5),
('Tree Pose',         'yoga',        'mat',            'core',       'Balance on one leg with arms overhead', 1, 5),
('Cobra Pose',        'yoga',        'mat',            'back',       'Lie face down, push chest up', 1, 5),
('Cat-Cow Stretch',   'yoga',        'mat',            'back',       'Alternate spine arch and round on all fours', 1, 10),
-- Flexibility
('Hip Flexor Stretch','flexibility', 'mat',            'legs',       'Kneel on one knee, push hips forward', 1, 30),
('Hamstring Stretch', 'flexibility', 'mat',            'legs',       'Seated forward fold', 1, 30),
('Shoulder Stretch',  'flexibility', 'none',           'shoulders',  'Pull one arm across chest', 1, 30),
('Neck Rolls',        'flexibility', 'none',           'shoulders',  'Slow circles with head', 1, 10),
('Seated Twist',      'flexibility', 'mat',            'back',       'Seated spinal rotation stretch', 1, 30)
) AS v(name, category, equipment, muscle_group, description, default_sets, default_reps)
WHERE NOT EXISTS (SELECT 1 FROM exercises LIMIT 1);
