-- Aroha schema, version 1: the tables as they stood when Flyway was introduced.
-- Written to be safe on a database that Hibernate (ddl-auto=update) already
-- created: every table, column and index is added only if it is missing.
-- From here on, change the schema with new V2__..., V3__... files; never edit this one.

CREATE TABLE IF NOT EXISTS daily_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS calories double precision NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS carbs double precision NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS fat double precision NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS log_date date NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS protein double precision NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS serving_grams double precision NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS logged_at timestamp(6) without time zone;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS meal_id bigint NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS meal_name character varying(255) NOT NULL;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS meal_slot character varying(255);

CREATE TABLE IF NOT EXISTS evolution_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE evolution_logs ADD COLUMN IF NOT EXISTS ep_at_stage_up integer NOT NULL;
ALTER TABLE evolution_logs ADD COLUMN IF NOT EXISTS staged_up_at timestamp(6) without time zone NOT NULL;
ALTER TABLE evolution_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE evolution_logs ADD COLUMN IF NOT EXISTS from_stage character varying(255) NOT NULL;
ALTER TABLE evolution_logs ADD COLUMN IF NOT EXISTS to_stage character varying(255) NOT NULL;

CREATE TABLE IF NOT EXISTS exercises (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS default_reps integer;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS default_sets integer;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS category character varying(255) NOT NULL;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS description character varying(255);
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS equipment character varying(255);
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS muscle_group character varying(255);
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS name character varying(255) NOT NULL;

CREATE TABLE IF NOT EXISTS habit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS completed boolean NOT NULL;
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS log_date date NOT NULL;
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS habit_id bigint NOT NULL;
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;

CREATE TABLE IF NOT EXISTS habits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE habits ADD COLUMN IF NOT EXISTS created_at timestamp(6) without time zone;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS color character varying(255) NOT NULL;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS icon character varying(255);
ALTER TABLE habits ADD COLUMN IF NOT EXISTS name character varying(255) NOT NULL;

CREATE TABLE IF NOT EXISTS meals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE meals ADD COLUMN IF NOT EXISTS calories_per_100g double precision;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS carbs_per_100g double precision;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS fat_per_100g double precision;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS fiber_per_100g double precision;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS is_custom boolean DEFAULT false NOT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS protein_per_100g double precision;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS typical_serving double precision;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS created_by bigint;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS brand character varying(255);
ALTER TABLE meals ADD COLUMN IF NOT EXISTS category character varying(255) NOT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS name character varying(255) NOT NULL;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS name_hindi character varying(255);
ALTER TABLE meals ADD COLUMN IF NOT EXISTS region character varying(255);
ALTER TABLE meals ADD COLUMN IF NOT EXISTS serving_unit character varying(255);

CREATE TABLE IF NOT EXISTS missions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE missions ADD COLUMN IF NOT EXISTS completed boolean NOT NULL;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS ep_reward integer NOT NULL;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS mission_date date NOT NULL;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS completed_at timestamp(6) without time zone;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS auto_key character varying(255);
ALTER TABLE missions ADD COLUMN IF NOT EXISTS category character varying(255) NOT NULL;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS title character varying(255) NOT NULL;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS type character varying(255) NOT NULL;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS created_at timestamp(6) with time zone NOT NULL;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS expires_at timestamp(6) with time zone NOT NULL;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS token_hash character varying(64) NOT NULL;

CREATE TABLE IF NOT EXISTS sleep_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS duration_hours double precision NOT NULL;
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS log_date date NOT NULL;
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS quality_rating integer NOT NULL;
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS sleep_time character varying(255);
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS wake_time character varying(255);

CREATE TABLE IF NOT EXISTS tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS carried_forward boolean NOT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed boolean NOT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS task_date date NOT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at timestamp(6) without time zone;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS linked_habit_id bigint;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_time character varying(255);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS title character varying(255) NOT NULL;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS age integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_calorie_goal integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_carb_goal integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_fat_goal integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_protein_goal integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS discipline_attr integer DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS evolution_points integer NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm double precision;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_date date;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_freeze_day date;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nutrition_attr integer DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_complete boolean;
ALTER TABLE users ADD COLUMN IF NOT EXISTS recovery_attr integer DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak integer NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS strength_attr integer DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_weight_kg double precision;
ALTER TABLE users ADD COLUMN IF NOT EXISTS water_goal_glasses integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_kg double precision;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamp(6) without time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level character varying(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_key character varying(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS dietary_preference character varying(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email character varying(255) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS evolution_stage character varying(255) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS experience_level character varying(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender character varying(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS health_goal character varying(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS name character varying(255) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password character varying(255) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_change_speed character varying(255);

CREATE TABLE IF NOT EXISTS water_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE water_logs ADD COLUMN IF NOT EXISTS daily_goal integer NOT NULL;
ALTER TABLE water_logs ADD COLUMN IF NOT EXISTS glasses integer NOT NULL;
ALTER TABLE water_logs ADD COLUMN IF NOT EXISTS log_date date NOT NULL;
ALTER TABLE water_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;

CREATE TABLE IF NOT EXISTS weight_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE weight_logs ADD COLUMN IF NOT EXISTS logged_date date NOT NULL;
ALTER TABLE weight_logs ADD COLUMN IF NOT EXISTS weight_kg double precision NOT NULL;
ALTER TABLE weight_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;

CREATE TABLE IF NOT EXISTS workout_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS log_date date NOT NULL;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS new_pr boolean DEFAULT false;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS reps integer NOT NULL;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS sets integer NOT NULL;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS weight_kg double precision;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS exercise_id bigint NOT NULL;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS logged_at timestamp(6) without time zone;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS category character varying(255);
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS exercise_name character varying(255) NOT NULL;

CREATE TABLE IF NOT EXISTS workout_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS actual_seconds integer NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS calories_burned double precision NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS exercises_completed integer NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS planned_minutes integer NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS total_sets integer NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS completed_at timestamp(6) without time zone NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS user_id bigint NOT NULL;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS exercise_names text;
ALTER TABLE workout_sessions ADD COLUMN IF NOT EXISTS workout_type character varying(255) NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS habit_logs_habit_id_log_date_key ON habit_logs (habit_id, log_date);
CREATE UNIQUE INDEX IF NOT EXISTS refresh_tokens_token_hash_key ON refresh_tokens (token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS sleep_logs_user_id_log_date_key ON sleep_logs (user_id, log_date);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS water_logs_user_id_log_date_key ON water_logs (user_id, log_date);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens (user_id);
